version: "3.3"

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    ports:
      - "8085:80"
    restart: always
    env_file: .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
